import Head from 'next/head';
import Image from 'next/image';
import { Button, Stack, Typography } from '@mui/material';
import Navbar from '../components/navbar/Navbar';
import { PageContainer } from '../styles/PageContainer';

export default function Home() {
    return (
        <PageContainer>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Navbar />

            <main>
                <Stack gap={2}>
                    <Typography variant='h2'>Dysk chmurowy w Azure.</Typography>

                    <Typography variant='body1'>
                        {/* eslint-disable-next-line react/no-unescaped-entities */}
                        Zaloguj się by wejść w "pliki" i przesłać / pobrać
                        pliki.
                    </Typography>
                </Stack>
            </main>
        </PageContainer>
    );
}
